/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 hotdog.glb
Author: Batuhan13 (https://sketchfab.com/Batuhan13)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hot-dog-stylized-435326b23a6240f48c2a48140522aa08
Title: Hot Dog Stylized
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/hotdog.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.Cube002_HotDog_0.geometry}
          material={materials.HotDog}
          position={[-2.25, 65.37, -26.04]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/hotdog.glb");
